/**
 * Dashboard Logic
 * Handles payment flow and number selection for regular users
 */

let currentUser = null;
let paymentStatus = null;
let numberMatrix = null;
let refreshInterval = null;
let currentScores = [];
let autoGeneratedNumbers = [];

document.addEventListener('DOMContentLoaded', async () => {
  // Initialize
  await init();

  // Set up event listeners
  document.getElementById('logoutBtn').addEventListener('click', handleLogout);
  document.getElementById('joinBolaoBtn').addEventListener('click', handleJoinBolao);
  document.getElementById('alreadyPaidBtn').addEventListener('click', handleAlreadyPaid);
  document.getElementById('autoGenerateBtn').addEventListener('click', handleAutoGenerate);
  document.getElementById('manualSelectBtn').addEventListener('click', handleManualSelect);
  document.getElementById('saveSelectionsBtn').addEventListener('click', handleSaveSelections);
  document.getElementById('saveAutoBtn').addEventListener('click', handleSaveAutoGenerated);
  document.getElementById('changeToManualBtn').addEventListener('click', handleManualSelect);
  document.getElementById('regenerateBtn').addEventListener('click', handleRegenerate);

  // Quota quantity change listener
  const quotaInput = document.getElementById('quotaQuantity');
  if (quotaInput) {
    quotaInput.addEventListener('input', updateTotalAmount);
  }

  // Auto-refresh every 30 seconds
  refreshInterval = setInterval(refreshData, 30000);
});

/**
 * Initialize dashboard
 */
async function init() {
  try {
    showLoading(true);

    // Check authentication
    currentUser = await checkAuth();

    if (!currentUser) {
      window.location.href = '/';
      return;
    }

    // Display user name
    document.getElementById('userName').textContent = `Olá, ${currentUser.name}!`;

    // Show admin panel button if user is admin
    if (currentUser.isAdmin) {
      const adminBtn = document.getElementById('adminPanelBtn');
      if (adminBtn) {
        adminBtn.style.display = 'inline-block';
      }
    }

    // Load initial data
    await loadPaymentStatus();
    await loadBolaoInfo();

  } catch (error) {
    console.error('Initialization error:', error);
    showToast('Erro ao carregar dashboard', 'error');
  } finally {
    showLoading(false);
  }
}

/**
 * Check if user is authenticated
 * @returns {object|null} User object or null
 */
async function checkAuth() {
  try {
    const response = await api.getCurrentUser();
    return response.success ? response.user : null;
  } catch (error) {
    return null;
  }
}

/**
 * Load payment status and show appropriate section
 */
async function loadPaymentStatus() {
  try {
    const response = await api.getPaymentStatus();

    paymentStatus = response.status;
    const quotaValue = response.quotaValue || 10.00;

    // Update payment section
    document.getElementById('quotaUnitValue').textContent = `R$ ${quotaValue.toFixed(2).replace('.', ',')}`;

    // Update quota quantity if user already joined
    if (response.participation && response.participation.quotaQuantity) {
      document.getElementById('quotaQuantity').value = response.participation.quotaQuantity;
      document.getElementById('totalAmount').textContent = response.participation.totalAmount.toFixed(2).replace('.', ',');
    } else {
      // Initialize total amount for new users
      updateTotalAmount();
    }

    // Show appropriate section based on status
    if (paymentStatus === 'not_joined') {
      showPaymentSection('join');
    } else if (paymentStatus === 'pending') {
      showPaymentSection('pending');
    } else if (paymentStatus === 'claimed') {
      showWaitingSection();
    } else if (paymentStatus === 'confirmed') {
      await showSelectionSection();
    }

  } catch (error) {
    console.error('Error loading payment status:', error);
    showToast('Erro ao carregar status do pagamento', 'error');
  }
}

/**
 * Show payment section with specific state
 * @param {string} state - 'join' or 'pending'
 */
function showPaymentSection(state) {
  const paymentSection = document.getElementById('paymentSection');
  const joinBtn = document.getElementById('joinBolaoBtn');
  const paidBtn = document.getElementById('alreadyPaidBtn');
  const statusDiv = document.getElementById('paymentStatus');

  paymentSection.style.display = 'block';

  if (state === 'join') {
    joinBtn.style.display = 'block';
    paidBtn.style.display = 'none';
    statusDiv.innerHTML = '';
  } else if (state === 'pending') {
    joinBtn.style.display = 'none';
    paidBtn.style.display = 'block';
    statusDiv.innerHTML = '<p class="info-text">⏳ Realize o pagamento via PIX e depois clique em "Já Paguei"</p>';
  }

  // Hide other sections
  document.getElementById('waitingSection').style.display = 'none';
  document.getElementById('selectionSection').style.display = 'none';
}

/**
 * Show waiting section
 */
function showWaitingSection() {
  document.getElementById('paymentSection').style.display = 'none';
  document.getElementById('waitingSection').style.display = 'block';
  document.getElementById('selectionSection').style.display = 'none';
}

/**
 * Show selection section with mode choice
 */
async function showSelectionSection() {
  try {
    document.getElementById('paymentSection').style.display = 'none';
    document.getElementById('waitingSection').style.display = 'none';
    document.getElementById('selectionSection').style.display = 'block';

    // Show mode choice by default
    document.querySelector('.selection-mode-choice').style.display = 'block';
    document.getElementById('manualSelectionArea').style.display = 'none';
    document.getElementById('autoGeneratedArea').style.display = 'none';

    // Preload scores for faster response
    const scoresResponse = await api.getScores();
    currentScores = scoresResponse.scores || [];

  } catch (error) {
    console.error('Error showing selection section:', error);
    showToast('Erro ao carregar seleção de números', 'error');
  }
}

/**
 * Update selected numbers display
 * @param {Array} numbers - Selected numbers
 */
function updateSelectedDisplay(numbers) {
  const sorted = numbers.sort((a, b) => a - b);

  document.getElementById('selectedCount').textContent = sorted.length;

  const listDiv = document.getElementById('selectedList');
  if (sorted.length === 0) {
    listDiv.innerHTML = '<p class="empty-text">Nenhum número selecionado</p>';
  } else {
    listDiv.innerHTML = sorted.map(num =>
      `<span class="selected-number">${num}</span>`
    ).join('');
  }
}

/**
 * Load bolao info (participant count, total funds)
 */
async function loadBolaoInfo() {
  try {
    const response = await api.getBolaoInfo();

    if (response.success && response.bolao) {
      const { confirmedCount } = response.bolao;
      const quotaValue = response.bolao.quotaValue || 10.00;
      const totalFunds = confirmedCount * quotaValue;

      document.getElementById('confirmedCount').textContent = confirmedCount;
      document.getElementById('totalFunds').textContent = totalFunds.toFixed(2);
    }
  } catch (error) {
    console.error('Error loading bolao info:', error);
  }
}

/**
 * Refresh data (called periodically)
 */
async function refreshData() {
  try {
    await loadPaymentStatus();
    await loadBolaoInfo();
  } catch (error) {
    console.error('Error refreshing data:', error);
  }
}

// Selection Mode Handlers

async function handleAutoGenerate() {
  try {
    showLoading(true);

    // Load scores if not loaded
    if (!currentScores || currentScores.length === 0) {
      const scoresResponse = await api.getScores();
      currentScores = scoresResponse.scores || [];
    }

    // Generate weighted random numbers
    const generateResponse = await api.generateNumbers();
    autoGeneratedNumbers = generateResponse.numbers || [];

    // Hide mode choice, show auto generated area
    document.querySelector('.selection-mode-choice').style.display = 'none';
    document.getElementById('manualSelectionArea').style.display = 'none';
    document.getElementById('autoGeneratedArea').style.display = 'block';

    // Display generated numbers
    displayGeneratedNumbers();

  } catch (error) {
    console.error('Error auto-generating:', error);
    showToast('Erro ao gerar números automaticamente', 'error');
  } finally {
    showLoading(false);
  }
}

async function handleRegenerate() {
  try {
    showLoading(true);

    // Generate new weighted random numbers
    const generateResponse = await api.generateNumbers();
    autoGeneratedNumbers = generateResponse.numbers || [];

    // Display the new numbers
    displayGeneratedNumbers();

    showToast('Novos números gerados!', 'success');

  } catch (error) {
    console.error('Error regenerating:', error);
    showToast('Erro ao gerar novos números', 'error');
  } finally {
    showLoading(false);
  }
}

function displayGeneratedNumbers() {
  const listDiv = document.getElementById('autoGeneratedList');
  listDiv.innerHTML = autoGeneratedNumbers.map(num => {
    const scoreData = currentScores.find(s => s.number === num);
    return `
      <div class="auto-number-card">
        <span class="auto-number">${num}</span>
        <div class="auto-number-details">
          <strong>Pontuação: ${scoreData ? scoreData.finalScore.toFixed(2) : 'N/A'}</strong>
          <small>Gerado aleatoriamente com peso baseado no score</small>
        </div>
      </div>
    `;
  }).join('');
}

async function handleManualSelect() {
  try {
    // Hide mode choice and auto area, show manual area
    document.querySelector('.selection-mode-choice').style.display = 'none';
    document.getElementById('autoGeneratedArea').style.display = 'none';
    document.getElementById('manualSelectionArea').style.display = 'block';

    // Load scores and selections if not already loaded
    if (!numberMatrix) {
      const [scoresResponse, selectionsResponse] = await Promise.all([
        api.getScores(),
        api.getMySelections()
      ]);

      currentScores = scoresResponse.scores || [];
      const selectedNumbers = selectionsResponse.numbers || [];

      // Initialize matrix
      numberMatrix = new NumberMatrix('numberMatrix');
      numberMatrix.onSelectionChange = updateSelectedDisplay;
      numberMatrix.maxSelections = 6; // Set maximum 6 numbers

      // Render matrix
      numberMatrix.render(currentScores, selectedNumbers);
      updateSelectedDisplay(selectedNumbers);
    }

  } catch (error) {
    console.error('Error showing manual selection:', error);
    showToast('Erro ao carregar seleção manual', 'error');
  }
}

async function handleSaveAutoGenerated() {
  try {
    showLoading(true);

    await api.selectNumbers(autoGeneratedNumbers);
    showToast('Números salvos com sucesso!', 'success');

    // Reload scores (popularity changed)
    const scoresResponse = await api.getScores();
    currentScores = scoresResponse.scores;

  } catch (error) {
    console.error('Error saving auto selections:', error);
    showToast(error.message || 'Erro ao salvar seleções', 'error');
  } finally {
    showLoading(false);
  }
}

// Event Handlers

/**
 * Update total amount based on quota quantity
 */
function updateTotalAmount() {
  const quotaQuantity = parseInt(document.getElementById('quotaQuantity').value) || 1;
  const quotaValue = parseFloat(document.getElementById('quotaUnitValue').textContent.replace('R$ ', '').replace(',', '.')) || 10;
  const totalAmount = (quotaQuantity * quotaValue).toFixed(2);

  document.getElementById('totalAmount').textContent = totalAmount.replace('.', ',');
}

async function handleJoinBolao() {
  try {
    showLoading(true);

    const quotaQuantity = parseInt(document.getElementById('quotaQuantity').value) || 1;

    // Validate quota quantity
    if (quotaQuantity < 1 || quotaQuantity > 10) {
      showToast('Quantidade de cotas deve estar entre 1 e 10', 'error');
      return;
    }

    await api.joinBolao(quotaQuantity);
    showToast(`Você entrou no bolão com ${quotaQuantity} ${quotaQuantity === 1 ? 'cota' : 'cotas'}! Agora realize o pagamento via PIX.`, 'success');

    await loadPaymentStatus();
  } catch (error) {
    console.error('Error joining bolão:', error);
    showToast(error.message || 'Erro ao entrar no bolão', 'error');
  } finally {
    showLoading(false);
  }
}

async function handleAlreadyPaid() {
  try {
    showLoading(true);

    await api.claimPaid();
    showToast('Pagamento registrado! Aguardando confirmação do administrador.', 'success');

    await loadPaymentStatus();
  } catch (error) {
    console.error('Error claiming payment:', error);
    showToast(error.message || 'Erro ao registrar pagamento', 'error');
  } finally {
    showLoading(false);
  }
}

async function handleSaveSelections() {
  try {
    if (!numberMatrix) return;

    const numbers = numberMatrix.getSelectedNumbers();

    if (numbers.length === 0) {
      showToast('Selecione pelo menos um número', 'warning');
      return;
    }

    showLoading(true);

    await api.selectNumbers(numbers);
    showToast(`${numbers.length} números salvos com sucesso!`, 'success');

    // Reload scores (popularity changed)
    const scoresResponse = await api.getScores();
    numberMatrix.render(scoresResponse.scores, numbers);

  } catch (error) {
    console.error('Error saving selections:', error);
    showToast(error.message || 'Erro ao salvar seleções', 'error');
  } finally {
    showLoading(false);
  }
}

async function handleLogout() {
  try {
    await api.logout();
    window.location.href = '/';
  } catch (error) {
    console.error('Logout error:', error);
    window.location.href = '/';
  }
}

// Utility Functions

function showLoading(show) {
  document.getElementById('loadingOverlay').style.display = show ? 'flex' : 'none';
}

function showToast(message, type = 'info') {
  const toast = document.getElementById('toast');
  toast.textContent = message;
  toast.className = `toast toast-${type}`;
  toast.style.display = 'block';

  setTimeout(() => {
    toast.style.display = 'none';
  }, 4000);
}

// Expose showToast globally for matrix.js
window.showToast = showToast;

// Cleanup on page unload
window.addEventListener('beforeunload', () => {
  if (refreshInterval) {
    clearInterval(refreshInterval);
  }
});
